publish SonarQube scan gate results to github

diff --git a/.github/workflows/assignment2.yml b/.github/workflows/assignment2.yml
--- a/.github/workflows/assignment2.yml
+++ b/.github/workflows/assignment2.yml
@@ -20,8 +20,35 @@ jobs:
         distribution: 'temurin'
         cache: maven
 
+    - name: Cache SonarQube Cloud packages
+      uses: actions/cache@v4
+      with:
+        path: ~/.sonar/cache
+        key: ${{ runner.os }}-sonar
+        restore-keys: ${{ runner.os }}-sonar
+
+    - name: Cache Maven packages
+      uses: actions/cache@v4
+      with:
+        path: ~/.m2
+        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+        restore-keys: ${{ runner.os }}-m2
+
     - name: Build and analyze
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rahulkausale_spring-boot-hello-world
+    
+        # Publish SonarQube Quality Gate results to GitHub
+    - name: SonarQube Quality Gate
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+        status=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=spring-boot-hello-world" | jq -r '.projectStatus.status')
+        if [ "$status" != "OK" ]; then
+          echo "Quality Gate failed: $status"
+          exit 1
+        else
+          echo "Quality Gate passed: $status"
+        fi
